using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using SkySpire.Api.Services;

namespace SkySpire.Api.Endpoints;

public static class AssetsEndpoints
{
    public static RouteGroupBuilder MapAssetsEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/assets").RequireAuthorization();

        group.MapPost("/pixellab/generate", async (
            [FromBody] PixelLabGenerateRequest body,
            PixelLabService pixellab,
            CancellationToken ct) =>
        {
            var description = string.IsNullOrWhiteSpace(body.Description) ? "hero" : body.Description.Trim();
            var action = string.IsNullOrWhiteSpace(body.Action) ? "idle" : body.Action.Trim();
            return Results.Ok(await pixellab.GenerateOrFallbackAsync(description, action, ct));
        });

        group.MapGet("/pixellab/{id}", async (string id, PixelLabService pixellab, CancellationToken ct) =>
        {
            var atlas = await pixellab.GetAtlasAsync(id, ct);
            return atlas is null ? Results.NotFound() : Results.Ok(atlas);
        });

        // Item icons are generated by the editor (dev); allow anonymous read so the editor can preview.
        group.MapGet("/items/{fileName}", (string fileName, PixelLabService pixellab) =>
        {
            var path = pixellab.GetItemIconFilePath(fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        // Monster sprites (PixelLab); anonymous read for editor preview.
        group.MapGet("/monsters/{fileName}", (string fileName, PixelLabService pixellab) =>
        {
            var path = pixellab.GetMonsterSpriteFilePath(fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        // Attribute card art (Gemini); anonymous read for editor preview + training UI.
        group.MapGet("/attributes/{fileName}", (string fileName, GeminiImageService gemini) =>
        {
            var path = gemini.GetAttributeCardFilePath(fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        // Floor backgrounds (Gemini); anonymous read for editor preview.
        group.MapGet("/floors/{fileName}", (string fileName, GeminiImageService gemini) =>
        {
            var path = gemini.GetFloorBackgroundFilePath(fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        // Race portraits (static under data/assets/races); anonymous read for hub Status.
        group.MapGet("/races/{fileName}", (string fileName, GeminiImageService gemini) =>
        {
            var path = gemini.GetRacePortraitFilePath(fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        // PixelLab generation drafts (editor pick/approve); anonymous read for preview.
        group.MapGet("/drafts/{draftId}/{fileName}", (string draftId, string fileName, PixelLabService pixellab) =>
        {
            var path = pixellab.GetDraftFilePath(draftId, fileName);
            return path is null ? Results.NotFound() : Results.File(path, "image/png");
        }).AllowAnonymous();

        return group;
    }
}

public sealed record PixelLabGenerateRequest(string? Description, string? Action);
